version: "3.9"

services:
  db:
    image: postgres:14.5-alpine
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=timesheet
      - POSTGRES_USER=timesheet
      - POSTGRES_PASSWORD=timesheet
  app:
    build: .
    environment:
      DJANGO_SETTINGS_MODULE: timesheet.settings
      SECRET_KEY: "django-insecure-1br405v7@&sc8l9rq2c68w&k)jdf!3z4l408#b3%-f8sjfl)e"
      DEBUG: "True"
      ALLOWED_HOSTS: "*"
      DATABASE_URL: "postgresql://timesheet:timesheet@db:5432/timesheet"
    volumes:
      - .:/app
    depends_on:
      - db
    command:
      [
        "./scripts/wait-for-it.sh",
        "db:5432",
        "-t",
        "120",
        "--",
        "./scripts/start-app.sh",
      ]

  web:
    image: nginx:1.22-alpine
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db-volume: