[tool.isort]
profile = "black"
force_single_line = true
skip_glob = "**/migrations/*.py, .venv/*"

[tool.black]
target-version = ["py310"]
extend-exclude = '''
(
    /(
        \.venv
        | migrations
        | \.git
    )/
)
'''